/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import UserPakage.*;
import Model.*;
import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MSII
 */
public class AccountScreen extends javax.swing.JFrame {
    Userr user ;
    Db db = new Db();
    ArrayList<Category> listCategory = new ArrayList<Category>(); 
    ArrayList<Product> listProduct = new ArrayList<Product>();
    String idCategory = null ;
    Counter c = new Counter();
    /**
     * Creates new form AccountScreen
     */
    
    public DefaultTableModel getModelTable(){
        DefaultTableModel model = (DefaultTableModel)tableComponent.getModel();
        return model ;
    } 
    
    public void clearValue(){
        idProductValue.setText("");
        nameProductValue.setText("");
        priceValue.setText("");
        numberOfCurrentvalue.setText("");
    }
    
    public void getCategory() throws SQLException{
        ResultSet resultSet = null;
        Statement statement = db.connectDbb().createStatement();
        String selectSql = "Select * from Category";
        resultSet = statement.executeQuery(selectSql);
        while(resultSet.next()){
            listCategory.add(new Category(resultSet.getString(1) , resultSet.getString(2)));
            selectElement.addItem(resultSet.getString(2));
        }
       
    }
    
    public void getAllProduct() throws SQLException{
        ResultSet resultSet = null;
        Statement statement = db.connectDbb().createStatement();
        String selectSql = "Select * from Product";
        resultSet = statement.executeQuery(selectSql);
        getModelTable().getDataVector().removeAllElements();
        while(resultSet.next()){
            getModelTable().addRow(new Object[]{resultSet.getString(1) ,resultSet.getString(2) ,resultSet.getString(3),
            resultSet.getDouble(4) ,resultSet.getInt(5)});
        }
    }
    
    public void updateUI(){
        
    }
    
    public AccountScreen(Userr us) throws SQLException {
        initComponents();
        this.user = us;
        this.pack();
        this.setLocationRelativeTo(null);
        valueUserName.setText(us.getNameUserr());
        getCategory();
        getAllProduct();
        
    }
    

    private AccountScreen() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valueUserName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableComponent = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        idProductValue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        selectElement = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameProductValue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        priceValue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        numberOfCurrentvalue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("AccountScreen");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("UserName :");

        valueUserName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tableComponent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProduct", "idCategory", "nameProduct", "price", "numberOfCurrent"
            }
        ));
        tableComponent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableComponentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableComponent);

        jButton1.setText("Add");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel3.setText("idProduct        :");

        selectElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectElementActionPerformed(evt);
            }
        });

        jLabel4.setText("Category        : ");

        jLabel5.setText("nameProduct :");

        jLabel6.setText("Price               :");

        jLabel7.setText("NumberOfCurrent :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(300, 300, 300))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(valueUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idProductValue, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(selectElement, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(nameProductValue)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceValue)
                                    .addComponent(jLabel7)
                                    .addComponent(numberOfCurrentvalue)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(valueUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idProductValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameProductValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numberOfCurrentvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void selectElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectElementActionPerformed
        
        System.out.println(selectElement.getSelectedItem());
        for (Category category : listCategory) {
            if(category.getNameCategory().equals(selectElement.getSelectedItem())){
                idCategory = category.getIdCategory();
            }
        }
        
        
    }//GEN-LAST:event_selectElementActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        ResultSet resultSet = null;
        Statement statement = null;
        try {
            PreparedStatement ps = db.connectDbb().prepareStatement("Insert into Product values(?,?,?,?,?)");
            ps.setString(1, idProductValue.getText());
            ps.setString(2, idCategory);
            ps.setString(3, nameProductValue.getText());
            ps.setDouble(4,Double.parseDouble(priceValue.getText()));
            ps.setInt(5, Integer.parseInt(numberOfCurrentvalue.getText()));
            ps.executeUpdate();
            getAllProduct();
//            getModelTable().addRow(new Object[]{idProductValue.getText() ,idCategory ,nameProductValue.getText(),
//            Double.parseDouble(priceValue.getText()) ,Integer.parseInt(numberOfCurrentvalue.getText())});
            clearValue();
            
        } catch (SQLException ex) {
            Logger.getLogger(AccountScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
            c.increment();
            
        if(c.getValue() == 1){
            jButton3.setText("Delete product");
            jLabel4.setVisible(false);
            selectElement.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            nameProductValue.setVisible(false);
            priceValue.setVisible(false);
            numberOfCurrentvalue.setVisible(false);
        }
        if(c.getValue() == 2)
        {
            try {
                PreparedStatement ps = db.connectDbb().prepareStatement("Delete from Product where idProduct=?");
                ps.setString(1, idProductValue.getText());
                ps.executeUpdate();
                getAllProduct();
                jButton3.setText("Delete");
                clearValue();
                jLabel4.setVisible(true);
                selectElement.setVisible(true);
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                nameProductValue.setVisible(true);
                priceValue.setVisible(true);
                numberOfCurrentvalue.setVisible(true);
                c.reset();
            } catch (SQLException ex) {
                Logger.getLogger(AccountScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        PreparedStatement ps;
        System.out.println(idProductValue.getText());
        try {
            ps = db.connectDbb().prepareStatement("update Product set idCategory = ? , nameProduct = ? , price = ? "
                    + ", numberOfCurrent = ? where idProduct = ? ");
            ps.setString(1, idCategory);
            ps.setString(2, nameProductValue.getText());
            ps.setDouble(3,Double.parseDouble(priceValue.getText()));
            ps.setInt(4, Integer.parseInt(numberOfCurrentvalue.getText()));
            ps.setString(5, idProductValue.getText());
            ps.executeUpdate();
            getAllProduct();
            clearValue();
            
        } catch (SQLException ex) {
            Logger.getLogger(AccountScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void tableComponentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableComponentMouseClicked
        DefaultTableModel model = (DefaultTableModel)tableComponent.getModel();
        int selectedRowindex = tableComponent.getSelectedRow();
        idProductValue.setText(model.getValueAt(selectedRowindex, 0).toString());
        nameProductValue.setText(model.getValueAt(selectedRowindex, 2).toString());
        priceValue.setText(model.getValueAt(selectedRowindex, 3).toString());
        numberOfCurrentvalue.setText(model.getValueAt(selectedRowindex, 4).toString());
    }//GEN-LAST:event_tableComponentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idProductValue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameProductValue;
    private javax.swing.JTextField numberOfCurrentvalue;
    private javax.swing.JTextField priceValue;
    private javax.swing.JComboBox<String> selectElement;
    private javax.swing.JTable tableComponent;
    private javax.swing.JLabel valueUserName;
    // End of variables declaration//GEN-END:variables
}
